param(
  [string]$EnvironmentPath = ".\environments\alz-platform",
  [string]$EvidencePath = ".\evidence"
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Path "$EvidencePath\raw" -Force | Out-Null

function Invoke-And-Capture {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name,
    [Parameter(Mandatory = $true)]
    [scriptblock]$Command
  )

  $rawPath = Join-Path $EvidencePath "raw\$Name.txt"
  $sanitizedPath = Join-Path $EvidencePath "$Name-sanitized.md"

  Write-Host "Running $Name..."
  $output = & $Command *>&1
  $exitCode = $LASTEXITCODE

  if ($null -eq $output) {
    "Command completed successfully with no output." | Tee-Object -FilePath $rawPath
  }
  else {
    $output | Tee-Object -FilePath $rawPath
  }

  powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\scripts\Sanitize-Evidence.ps1 `
    -InputPath $rawPath `
    -OutputPath $sanitizedPath

  if ($exitCode -ne 0) {
    throw "$Name failed with exit code $exitCode. Review $sanitizedPath."
  }
}

Invoke-And-Capture -Name "public-repo-safety" -Command {
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\scripts\Test-PublicRepoSafety.ps1
}

Invoke-And-Capture -Name "terraform-fmt" -Command {
  terraform "-chdir=$EnvironmentPath" fmt -recursive -check
}

Invoke-And-Capture -Name "terraform-init" -Command {
  terraform "-chdir=$EnvironmentPath" init -backend=false -upgrade
}

Invoke-And-Capture -Name "terraform-validate" -Command {
  terraform "-chdir=$EnvironmentPath" validate
}

$summaryPath = Join-Path $EvidencePath "predeployment-validation-summary.md"
@"
# Predeployment Validation Summary

Generated by `scripts/Run-PredeploymentValidation.ps1`.

## Checks

- Public repo safety: see `public-repo-safety-sanitized.md`
- Terraform format: see `terraform-fmt-sanitized.md`
- Terraform init without backend: see `terraform-init-sanitized.md`
- Terraform validate: see `terraform-validate-sanitized.md`

## What This Proves

- The repository has no obvious committed local state, key, or secret files.
- Terraform can initialize modules without configuring a remote backend.
- Terraform syntax and provider/module wiring validate locally.

## What This Does Not Prove

- Azure deployment succeeded.
- Azure permissions are configured.
- Tenant-specific values are correct.
- Runtime network or policy behavior has been tested in Azure.
"@ | Set-Content -LiteralPath $summaryPath -Encoding UTF8

Write-Host "Predeployment validation evidence written to $EvidencePath"
